---
- name: Install Multiple packages
  hosts: dev
  become: true
  remote_user: ec2-user

  tasks:
    - name: Install Multiple packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - git
        - curl-minimal
