---
- name: Run task Only If OS is Amazon Linux
  hosts: dev
  become: true
  remote_user: ec2-user

  tasks:
    - name: Update packages
      ansible.builtin.package:
        update_cache: yes
      when: ansible_distribution == "Amazon"