# #####################################
# Installs Apache only on supported OS.
# #####################################

---
- name: Fail if OS is unsupported
  ansible.builtin.fail:
    msg: "This role only supports: {{ apache_supported_os }}"
  when: ansible_distribution not in apache_supported_os

- name: Install Apache package
  ansible.builtin.package:
    name: "{{ apache_pkg_map[ansible_distribution] }}"
    state: present

- name: Enable and start Apache service
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
