---
- name: Install and start Apache and FTP services
  hosts: dev
  become: true

  vars:
    mail_services: 
      - apache2
      - vsftpd
    packages:
      - apache2
      - vsftpd

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
        
    - name: Ensure Apache and FTP services are running and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ mail_services }}"
