---
- name: "with_item"
  hosts: dev
  become: true

  vars:
    data:
      - user1
      - user2
      - user3
      - user4
      - user5

  tasks:
    - name: with item
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ data }}"
