
---
- name: Ansible handlers
  hosts: dev        # run on all servers in the dev group
  become: true      # escalate to root
  gather_facts: yes # collect system facts (OS, memory, mounts, etc.)

  tasks:
    - name: Restart a service
      ansible.builtin.service:   
        name:  notaservice
        state: restart
      ignore_errors: yes  

    - name: copy a file   
      ansible.builtin.copy:   
        src: /home/ec2-user/a15_Task_Control/a18_00_script.sh
        dest: /tmp

    - name: Run the script
      ansible.builtin.shell:  sh /tmp/a18_00_script.sh
      register: command_result 
      failed_when: "'Password missing' in command_result.stdout"

    - name: Task Failure condition
      ansible.builtin.debug: msg="{{ command_result.stdout }}"

    - name: Restart the apache2 server
      ansible.builtin.service: 
        name: apache2
        state: restarted


