---
- name: Ensure user exists
  hosts: dev
  remote_user: ansadmin
  become: yes

  tasks:
    - name: create user account devops
      ansible.builtin.user:
        name: devops 
        state: present
