---
- name: Copy a file to remote machine using copy module
  hosts: dev
  become: yes
  remote_user: ec2-user
  gather_facts: true

  tasks:
    - name: copy demo.txt to /tmp
      ansible.builtin.copy:
        src: /home/ec2-user/a05_Deploy_Files/demo.txt #Absolute path on control node
        dest: /tmp
        mode: '0644'
        owner: root
        group: root