---
- name: Install a package and prints the result
  hosts: dev
  become: yes
  remote_user: ec2-user     # user 

  tasks:

    - name: a01. Install httpd package
      ansible.builtin.dnf: 
        name: httpd
        state: installed
      register: install_result

    - name: a02. Show Installation Result
      debug:
        var: install_result

