- name: Simple Playbook To Print Hello Message
  # hosts: 192.168.10.5
  # hosts: client01, client02
  # hosts: all
  # hosts: dev, !client02
  hosts: dev
  become: yes
  remote_user: ec2-user
  gather_facts: true      # Required because the template uses ansible_facts

  tasks:
    - name: Configure custom /etc/motd
      template:
        src: a13_Template_Memory_Processor_Count.j2   # Jinja2 template file
        dest: /etc/motd
        mode: 0644
        owner: root
        group: root

    - name: Check file informations (stat)
      stat:
        path: /etc/motd
      register: motd_info

    - name: Display file result
      debug:
        var: motd_info
